print ("Questtion 1: How to check a variable's type?")
print ("Answer:")
print ("We use type() function:")
print (" type(variable's name)")
print()
print("Question 2: In what case, you will get SyntaxError from the compiler telling you that some of your variable has invalid name? Can you give 3 example of invalid name?")
print("Answer:")
print("- An invalid variable's name is a name starts with number, contains illegal character or is one of 29 keywords . If one or more of your variables's name is invalid, the compiler will give 'SyntaxError'")
print ("-Examples of invalid variable's name:")
print ("69hello")
print("iwant$")
print("else")